server:
  port: 8766
spring:
  application:
    name: spring-boot-admin-sample-eureka
  profiles:
    active:
      - secure
            
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://118.24.186.220:1111/eureka

management: 
  endpoint: 
    health: 
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

security2:
    user:
      name: "tenderadmin"
      password: "cqcyit81390088"

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: ${security2.user.name}
      password: ${security2.user.password}
eureka:
  instance:
    metadata-map:
      user.name: ${security2.user.name}
      user.password: ${security2.user.password}